import mysql.connector
import logging
import sys
from flask_backend.database_config import HOST, USER, PASSWORD, DATABASE

# This class build as Singleton is responsible for handling database connection
class DatabaseConnector:
    # establishing connection to database
    try:
        database = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)

    except mysql.connector.Error as e:
        logging.critical('Connection to database has not been established: ' + str(e))
        sys.exit()

    # This method executes the query that adds new user to database
    @staticmethod
    def insert_into_users(username, email, password_hash, is_active, timestamp):
        query = 'INSERT INTO users (username, email, password_hash, is_active, timestamp) VALUES (%s, %s, %s, %s, %s)', (username, email, password_hash, is_active, timestamp)
        print(query)

        try:
            cursor = DatabaseConnector.database.cursor()
            cursor.execute(*query)
            DatabaseConnector.database.commit()
        except (mysql.connector.Error, AttributeError) as e:
            logging.error('Query has not been executed: ' + str(e))

    # This method executes the query that checks if user with specified username already exists
    @staticmethod
    def select_from_users_by_username(username):
        query = 'SELECT * FROM users WHERE username=%s', (username,)
        print(query)
        try:
            cursor = DatabaseConnector.database.cursor()
            cursor.execute(*query)
            data = []
            for element in cursor:
                data.append(element)
            return data
        except (mysql.connector.Error, AttributeError) as e:
            logging.error('Query has not been executed: ' + str(e))

    # This method executes the query that checks if user with specified email already exists
    @staticmethod
    def select_from_users_by_email(email):
        query = 'SELECT * FROM users WHERE email=%s', (email,)
        print(query)
        try:
            cursor = DatabaseConnector.database.cursor()
            cursor.execute(*query)
            data = []
            for element in cursor:
                data.append(element)
            return data
        except (mysql.connector.Error, AttributeError) as e:
            logging.error('Query has not been executed: ' + str(e))

    # This method executes the query that sets user as active
    @staticmethod
    def update_users_account_activation(email):
        query = 'UPDATE users SET is_active=True WHERE email=%s', (email,)
        print(query)

        try:
            cursor = DatabaseConnector.database.cursor()
            cursor.execute(*query)
            DatabaseConnector.database.commit()
        except (mysql.connector.Error, AttributeError) as e:
            logging.error('Query has not been executed: ' + str(e))

    # This method executes the query that adds new user's product list to database
    @staticmethod
    def insert_into_products_history(user_id, name, link, price, photo, timestamp):
        query = 'INSERT INTO products_history (user_id, name, link, price, photo, timestamp) VALUES (%s, %s, %s, %s, %s, %s)', (user_id, name, link, price, photo, timestamp)
        print(query)

        try:
            cursor = DatabaseConnector.database.cursor()
            cursor.execute(*query)
            DatabaseConnector.database.commit()
        except (mysql.connector.Error, AttributeError) as e:
            logging.error('Query has not been executed: ' + str(e))

    # This method executes the query that lists all product lists generated by specified user
    @staticmethod
    def select_from_products_history(user_id):
        query = 'SELECT * FROM products_history WHERE user_id=%s ORDER BY timestamp desc', (user_id,)
        print(query)
        try:
            cursor = DatabaseConnector.database.cursor()
            cursor.execute(*query)
            data = []
            for element in cursor:
                data.append(element)
            return data
        except (mysql.connector.Error, AttributeError) as e:
            logging.error('Query has not been executed: ' + str(e))

    # This method executes the query that performs database retention
    @staticmethod
    def execute_database_retention():
        query_1 = 'DELETE FROM products_history WHERE timestamp < now() - INTERVAL 6 MONTH'
        print(query_1)
        #query_2 = 'DELETE FROM users WHERE timestamp < now() - INTERVAL 6 MONTH'
        #print(query_2)

        try:
            cursor = DatabaseConnector.database.cursor()
            cursor.execute('SET SQL_SAFE_UPDATES = 0')
            cursor.execute(*query_1)
            #cursor.execute(*query_2)
            cursor.execute('SET SQL_SAFE_UPDATES = 1')
            DatabaseConnector.database.commit()
        except (mysql.connector.Error, AttributeError) as e:
            logging.error('Query has not been executed: ' + str(e))